🎉 아바타 컴포넌트 개발
prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG pull request #33
Opened 2023-09-08 09:21 UTC by khj0426

## - 목적
여러 곳에서 사용될 수 있는 아바타 컴포넌트를 개발했습니다.

관련 이슈: #26 

<br>

## - 주요 변경 사항

```ts
type AvatarProps = {
  color?: string //배경색
  shape?: 'rounded' | 'circle' | 'square' //아바타의 형태
  size: number //아바타의 크기
  src?: string //이미지 경로
  text?: string //아바타 옆에 붙어있는 텍스트
  textSize?: 'small' | 'medium' | 'large' //텍스트 크기 설정
  textColor?: string //텍스트 색상 지정
  textDirection?: 'top' | 'medium' | 'bottom' //어디에 텍스트가 위치하는지?
  style?: CSSProperties //기타 스타일
}
```

- 아바타 컴포넌트를 개발했습니다. 아래와 같이 쓰면 됩니다

```jsx
 <Avatar size={50}  />
 <Avatar size={50}  text = "포청천천" textColor = "red" textDirection = "top" />
 <Avatar size={50}  text = "포청천천" textColor = "red" textDirection = "top"  src = "포청천이미지.png" />
```

## 기타 사항 (선택)

- 

<br>

## - 스크린샷 (선택)

- shape : 'circle' 일떄

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/bb228564-3ba4-4b4b-b8e6-2bb8df0f8a08)

- shape : 'rounded' 일떄

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/9d3bdc29-4968-424b-b9bc-64b43d5fe48a)

- shape : 'square' 일떄

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/905655c5-964a-46c6-912d-5e9f62efd499)

- text가 있을때 + textDirection이 top일떄

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/1f15f3c7-90ab-42d6-a1f2-561c445f957c)

- text가 있고 textDirection이 medium일떄

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/09d71598-d9b8-405b-a3b4-89a32c2c5c07)

2023-09-08 14:51 UTC, oaoong approved these changes
좋습니다!!

개인적으로는 textSize의 크기를 세가지로 제한하셨 듯이 avatar 크기도 프로젝트 내의 케이스로 제한하면 사용하시면서 통일성을 강제하기 좋을 것 같습니다!

2023-09-09 06:23 UTC, Lim-JiSeon requested changes
죄송합니다..... 효중님 화이팅...!!

2023-09-09 06:23 UTC, Lim-JiSeon commented on src/components/atoms/Avatar/index.tsx
> +      </span>
보통 이 부분에 텍스트가 한 줄 더 들어갈 수 있습니다. (사용자 목록, 알림 등등 디자인 참고)
아바타 구조는 총 3가지 정도인 것 같습니다.
1. 아바타 사진만 있는 경우
2. 아바타 사진과 닉네임만 있는 경우
3. 아바타 사진과 닉네임, 그 외 텍스트가 있는 경우

그래서 혹시 텍스트가 들어갈 공간을 하나 더 만들어 주실 수 있을까요...? ㅠㅜ 
이제 이럴 경우에는 닉네임 즉 span은 top에 정렬되고 그 외 텍스트는 bottom에 정렬될 것 같습니다. 

```javascript
<div className="avatar__container">
      <div
        style={{ ...style, width: size, height: size }}
        className={avatarClassName}
      >
        <Image
          src={src || Assets.PCCImage}
          alt="아바타"
          fill
          className={`avatar__image shape-${shape}`}
          style={{
            backgroundColor: color,
          }}
        />
      </div>
      <span
        className={`color-${textColor} text-${textDirection} textSize-${textSize}`}
        style={{
          color: textColor,
        }}
      >
        {text}
      </span>
      // 추가한다면 ? 
     <span
       className={`color-${textColor} text-${textDirection} textSize-${textSize}`}
        style={{
          color: textColor,
        }}
    >
     {content}
    </span>
</div>
```

2023-09-09 06:23 UTC, Lim-JiSeon commented on src/components/atoms/Avatar/index.tsx
> +      </span>
1. 아바타 사진
<img width="203" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/661d7aa7-83f1-481a-8134-23e4a302eeaa">

2. 아바타 사진, 닉네임
<img width="79" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/2d8fd2fa-93aa-46fa-8f89-652c88536119">

3. 아바타 사진, 닉네임, 그 외 텍스트
<img width="245" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/f14bea25-11c3-4e51-bec8-4087bdeb83a3">

2023-09-09 08:11 UTC, khj0426 commented on src/components/atoms/Avatar/index.tsx
> +      </div>
최대한 직관적이게 분리했습니다.  Profile와 Description으로 분리했어요!

```tsx
import React, { CSSProperties } from 'react'
import Image from 'next/image'
import Assets from '@/config/assets'
import './index.scss'

type AvatarProps = {
  color?: string
  shape?: 'rounded' | 'circle' | 'square'
  size: number
  src?: string
  alt?: string
  text?: string
  textSize?: 'small' | 'medium' | 'large'
  textColor?: string
  textDirection?: 'top' | 'medium' | 'bottom'
  textStyle?: CSSProperties
  style?: CSSProperties
  children?: React.ReactNode
}

type AvatarTextProps = Pick<
  AvatarProps,
  'text' | 'textStyle' | 'textDirection' | 'textColor' | 'textSize'
>

export default function Avatar({
  color,
  shape = 'circle',
  size = 100,
  src,
  alt,
  text,
  textColor,
  textStyle,
  textSize,
  textDirection,
  style,
  children,
}: AvatarProps) {
  return (
    <div className="avatar__container">
      <Profile
        size={size}
        alt={alt}
        src={src}
        color={color}
        shape={shape}
        style={style}
      />

      {children}
      <Description
        text={text}
        textSize={textSize}
        textColor={textColor}
        textStyle={textStyle}
        textDirection={textDirection}
      />
    </div>
  )
}
```

2023-09-09 08:15 UTC, khj0426 commented on src/components/atoms/Avatar/index.tsx
> +      </span>
일단 아바타에 여러 문자열이 들어가는 것은 고려하지 않았슴니다.. 하나의 문자열만 넣게 했는데,
1번 2번의 경우 아바타 컴포넌트에서 바로 사용할 수 있어요!

다만 3번의 경우 children으로 다음과 같이 넣는다면 3번의 형태가 나오는데, 음 이를 따로 atom으로 뺼지 궁금하네욤..

```tsx
//1번
<Avatar size = {50} />

//2번
<Avatar size={50} text="pcc" textDirection="top" textSize="large" />

//3번
<Avatar size={50}>
  <div
    style={{
      display: 'flex',
      gap: '5px',
      alignItems: 'center',
      flexDirection: 'column',
      justifyContent: 'space-around',
      marginLeft: '100px',
    }}
  >
    <div>text1</div>
    <div>text2</div>
  </div>
</Avatar>
```

각각 1,2,3번의 상태임니다!

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/2ebd434e-22a1-4b52-82d8-1887f3475994)

2023-09-09 08:17 UTC, khj0426 commented on src/components/atoms/Avatar/index.tsx
> +}
각각 small medium large케이스로 분리했습니다.

```ts
  textSize?: 'small' | 'medium' | 'large'
````

2023-09-09 08:50 UTC, leeminhee119 commented on src/components/atoms/Avatar/index.tsx
> +      </span>
3번의 경우 사용하는 쪽에서 children으로 스타일이 지정된 div를 직접 넣어줘야 하는 건가요 ?.?

텍스트가 붙었을 때의 케이스가
```
1. 이름 텍스트 하나만 있는 경우: 가운데 정렬
2. 이름 및 기타 텍스트 두 개가 있는 경우: 각각 위 아래 정렬
```
두 가지 뿐이기 때문에 textDirection을 매번 props로 따로 받기보다는, 텍스트가 한 개인 경우 / 두 개인 경우 (ex: `textSub` 같은 선택적 props를 둔다든가?) 로 나눠서 각각의 케이스에 맞게 textDirection은 자동으로 컴포넌트 내에서 처리해주는 게 좋지 않을까 싶습니다!

2023-09-09 08:57 UTC, leeminhee119 approved these changes

2023-09-09 11:06 UTC, khj0426 commented on src/components/atoms/Avatar/index.tsx
> +      </span>
1번의 경우 기본값으로 가운데 정렬을 하도록하고, 2번의 경우에는 민희님 말씀처럼 `subText`라는 프롭을 새로 만들어서 처리하도록 하겠습니다 !! 

뭔가 민희님 말씀대로 하면 사용하기 더 편할거 같아서 텍스트가 2개인 경우도 고려해서 커밋하고 머지할게요 🦖

2023-09-09 12:37 UTC, khj0426 commented on src/components/atoms/Avatar/index.tsx
> +      </span>
subTitle props를 만들고 두번쨰 텍스트를 넣을 수 있게 바꾸었습니다. 

그리고 children으로 스타일이 지정된 div를 넣지 않고, `textStyle`로 두 텍스트의 레이아웃을 조절 할 수 있습니다.

예를들어 위의 사진과 같이 2개의 텍스트가 수직으로 배치되고 서로 떨어지게 하려면

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/59411107/2b3d2a74-a711-496d-ba4d-840cbd31a454)

다음과 같이 `textStyle props`를 지정하면 됩니다!.!

```tsx
<Avatar
  text="제목"
  subText="부제목"
  size={100}
  shape="rounded"
  textStyle={{
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  }}
/>
```

2023-09-09 20:03 UTC, Lim-JiSeon approved these changes

2023-09-09 20:04 UTC, Lim-JiSeon commented on src/components/atoms/Avatar/index.tsx
> +      </span>
번거로우셨을텐데 감사합니다!! 👍 👍 👍

2023-09-11 03:49 UTC, merged