Feat 16 router
prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG pull request #34
Opened 2023-09-08 09:37 UTC by Lim-JiSeon

## - 목적
관련 이슈: #
- #16

<br>

## - 주요 변경 사항
- Next.js router 경로 정의

## 기타 사항 (선택)
메인 페이지 : /
로그인 페이지 : /signin
회원가입 페이지 : /signup
포스트 상세 페이지 : /post/[postid] (ex : /post/1)
글쓰기 페이지 : /post/new
검색 결과 페이지 : /search/[keyword] (ex : /search/고기)
내 계정 수정 페이지 : /user/edit/profile
비밀번호 수정 페이지 : /user/edit/password
프로필 페이지 : /user/mypage

<br>

## - 스크린샷 (선택)
<img width="1280" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/7b1ebca4-acbb-40d8-bc31-cffd2c4b6937">

2023-09-08 09:41 UTC, khj0426 approved these changes
고생하셨슴니다 👍 👍

2023-09-08 14:44 UTC, oaoong requested changes

2023-09-08 14:45 UTC, oaoong commented on src/config/paths.ts
> +  SEARCH: '/search/[keyword]',
위 방식으로 통일하는 것도 고려할 수 있을 것 같은데, 지선님 의견대로 수정해보시고 re-requst review 부탁드립니다.

2023-09-09 05:58 UTC, Lim-JiSeon commented on src/config/paths.ts
> +  SEARCH: '/search/[keyword]',
HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  postDetail: (id: string) => `/post/${id}`,
  postNew: () => '/post/new',
  search: (keyword: string) => `search/${keyword}`,
  editProfile: () => '/user/edit/profile',
  editPassword: () => '/user/edit/password',
  myPage: () => '/user',
  
 이런 식으로 수정했습니다.

2023-09-09 06:06 UTC, Lim-JiSeon commented
둘 중에 하나를 고민 중입니다. 어떤 것을 더 선호하시나요?

 ```javascript
editProfile: () => '/user/edit/profile',
editPassword: () => '/user/edit/password',
myPage: () => '/user',
```

```javascript
EDITPROFILE: '/user/edit/profile',
EDITPASSWORD: '/user/edit/password',
MYPAGE: '/user',
```

첫 번째 방식에서는 APP_PATH.myPage() 이런 식으로 사용하고, 
두 번째 방식에서는 APP_PATH.MYPAGE 이런 식으로 사용하게 됩니다. 이 3가지 변수만 고민 중이고 나머진 위에 새로 리팩토링해 수정한 코드로 고정할 예정입니다. PR 부탁드립니다.

2023-09-09 06:14 UTC, khj0426 commented
> 둘 중에 하나를 고민 중입니다. 어떤 것을 더 선호하시나요?
> 
> ```js
> editProfile: () => '/user/edit/profile',
> editPassword: () => '/user/edit/password',
> myPage: () => '/user',
> ```
> 
> ```js
> EDITPROFILE: '/user/edit/profile',
> EDITPASSWORD: '/user/edit/password',
> MYPAGE: '/user',
> ```
> 
> 첫 번째 방식에서는 APP_PATH.myPage() 이런 식으로 사용하고, 두 번째 방식에서는 APP_PATH.MYPAGE 이런 식으로 사용하게 됩니다. 이 3가지 변수만 고민 중이고 나머진 위에 새로 리팩토링해 수정한 코드로 고정할 예정입니다. PR 부탁드립니다.

저의 생각은 파스칼 케이스 보단 두번쨰 방법이 나은 것 같습니다. APP_PATH도 상수고 프로퍼티에만 파스칼 케이스를 적용하는것이 일관적이진 않은 것 같아요! 두번쨰에 한표 던지겠습니다

2023-09-09 09:06 UTC, leeminhee119 commented
> > 둘 중에 하나를 고민 중입니다. 어떤 것을 더 선호하시나요?
> > ```js
> > editProfile: () => '/user/edit/profile',
> > editPassword: () => '/user/edit/password',
> > myPage: () => '/user',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > EDITPROFILE: '/user/edit/profile',
> > EDITPASSWORD: '/user/edit/password',
> > MYPAGE: '/user',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 첫 번째 방식에서는 APP_PATH.myPage() 이런 식으로 사용하고, 두 번째 방식에서는 APP_PATH.MYPAGE 이런 식으로 사용하게 됩니다. 이 3가지 변수만 고민 중이고 나머진 위에 새로 리팩토링해 수정한 코드로 고정할 예정입니다. PR 부탁드립니다.
> 
> 저의 생각은 파스칼 케이스 보단 두번쨰 방법이 나은 것 같습니다. APP_PATH도 상수고 프로퍼티에만 파스칼 케이스를 적용하는것이 일관적이진 않은 것 같아요! 두번쨰에 한표 던지겠습니다

근데 그러면 postDetail이나 search의 경우처럼 매개변수가 필요한 경우는 어떻게 할까요?
지금 home, login, register만 대문자 상수로 처리돼있는데 이 세 개만 상수로 두신 이유도 궁금합니다!

2023-09-09 12:57 UTC, oaoong commented
> 둘 중에 하나를 고민 중입니다. 어떤 것을 더 선호하시나요?
> 
> ```js
> editProfile: () => '/user/edit/profile',
> editPassword: () => '/user/edit/password',
> myPage: () => '/user',
> ```
> 
> ```js
> EDITPROFILE: '/user/edit/profile',
> EDITPASSWORD: '/user/edit/password',
> MYPAGE: '/user',
> ```
> 
> 첫 번째 방식에서는 APP_PATH.myPage() 이런 식으로 사용하고, 두 번째 방식에서는 APP_PATH.MYPAGE 이런 식으로 사용하게 됩니다. 이 3가지 변수만 고민 중이고 나머진 위에 새로 리팩토링해 수정한 코드로 고정할 예정입니다. PR 부탁드립니다.

저는 다 카멜로 통일하면 좋을 것 같아요. 사용성에 큰 영향은 해결됐으니 approve 하겠습니다.

2023-09-09 12:57 UTC, oaoong approved these changes

2023-09-09 20:19 UTC, Lim-JiSeon commented
최종 수정본입니다!
- 하나로 통일 되었으면 좋겠다
- 카멜케이스였으면 좋겠다
란 의견을 반영했습니다. 

참고로 변수명 논의라 로직 상의 문제나 별도의 approve를 또 받을 필요는 없을 거 같다고 판단했기 때문에 다음과 같이 변경한 뒤 merge했습니다!

home: '/',
login: '/login',
register: '/register',
postDetail: (id: string) => /post/${id},
postNew: () => '/post/new',
search: (keyword: string) => search/${keyword},
editProfile: () => '/user/edit/profile',
editPassword: () => '/user/edit/password',
myPage: () => '/user',

2023-09-09 20:29 UTC, merged