🎉 회원가입 폼 컴포넌트 구현
prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG pull request #57
Opened 2023-09-11 18:04 UTC by bomi8489

## - 목적
관련 이슈: #30 
- 회원가입 폼 컴포넌트를 구현했습니다

<br>

## - 주요 변경 사항

-

## 기타 사항 (선택)

- 로그인 폼 이슈에서 생성한 molcules 컴포넌트를 사용하느라 #29 브랜치에서 브랜치를 만들어 작업을 한 탓인지 develop에 PR을 날릴때 바로 승인이 되는 것같네요 일단은 PR을 날리도록 하겠습니다.

<br>

## - 스크린샷 (선택)

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/66124037/4d1c5d9f-7a52-4c0f-a185-cbc911b5dec6)

2023-09-12 04:36 UTC, khj0426 approved these changes
고생하셨습니다!! 충돌 처리하느라 고생하셨어요..! 👍 👍

2023-09-12 04:36 UTC, khj0426 commented on src/components/molcules/SignInput/index.tsx
> +>(
💯 👍 👍 👍

2023-09-12 04:36 UTC, khj0426 commented on src/components/molcules/SignInput/index.tsx
> +SignInput.displayName = 'SignInput'
오오.. displayName은 어떤 용도인가요?!?! 처음 봐서 궁금합니다.!

2023-09-12 04:36 UTC, khj0426 commented on src/components/molcules/SignTitle/index.scss
> +  color: #E2AF3C;
요 부분은 민희님이 만들어 주신 믹스인을 쓸 수도 있을 거 같아요!

2023-09-12 04:58 UTC, bomi8489 commented on src/components/molcules/SignInput/index.tsx
> +SignInput.displayName = 'SignInput'
컴포넌트를 forwardRef로 감싸면 반환되는 SignInput 객체에 displayName이 undefined가 되어 오류를 발생시킨다고합니다. 해결책으로 여러가지가 있었는데 eslint 무시코드를 사용하기보다 displayName을 직접 할당해주면 된다고 하더라구요. 해당 오류는 React.memo를 사용할때도 발생한다고 하네요 정확한 이유는 잘 모르겠습니다...!

2023-09-12 04:58 UTC, bomi8489 commented on src/components/molcules/SignTitle/index.scss
> +  color: #E2AF3C;
네!!!

2023-09-12 05:25 UTC, leeminhee119 requested changes
색상 관련 css는 mixin을 사용 부탁드립니다 !! ([사용방법](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/pull/37))

2023-09-12 06:05 UTC, Lim-JiSeon reviewed
로그인 폼과 형식이 비슷해서 리뷰도 비슷한 것 같습니다 :)
로그인 폼 수정하시면서 회원가입 폼도 같이 수정하시면 좋을 것 같아요!

2023-09-12 06:05 UTC, Lim-JiSeon commented on src/components/organisms/LogInForm/index.tsx
> +export default LogInForm
로그인 폼 pr에서 했던 리뷰 참고해서 비슷하게 수정하시면 될 것 같습니당~!

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/assets/83554018/ec91c80f-f65f-4d39-874e-eb573f36b881)

2023-09-13 06:59 UTC, Lim-JiSeon reviewed
피드백 수정하셨다면 민희님 approve 받은 뒤 머지하시면 될 것 같습니다~!

2023-09-13 08:22 UTC, leeminhee119 approved these changes

2023-09-13 08:25 UTC, closed without merging